### ISSUE TITLE
Day offset calculation crashes if it extends into next year

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#1]
The mod crashes when calculating a day offset that extends into the next year (e.g. +5 days on Winter 24):

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Pathoschild.LookupAnything.GameHelper.GetDayOffset(Int32 offset, Int32 daysInSeason)
at Pathoschild.LookupAnything.Framework.Subjects.FarmAnimalSubject.<GetData>d__2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at Pathoschild.LookupAnything.Components.LookupMenu..ctor(ISubject subject, Metadata metadata)
at Pathoschild.LookupAnything.LookupAnythingMod.ShowLookup()
```

[Reported via forums](http://community.playstarbound.com/threads/smapi-lookup-anything.122929/page-4#post-3037047).

**Comment by Pathoschild** [comment]
Fixed in the upcoming 1.5 release via 5d94d368f3d2c5ae55f937ce226533a9c14194c8.
