### ISSUE TITLE
[Look Up Anything] Just Stopped Working

### ISSUE THREAD

**Issue by pollywogpixels** [Pathoschild/LookupAnything#131]
This Is an issue I had with Look Up Anything. I installed the more crops mod and I couldn't look up anything besides like myself. I removed the more crops and it worked for a bit but when I was messing with other mods is just stopped. I load all my content mods through XNB loader. I don't know how to fix it or what went wrong.

 
![screenshot 93](https://user-images.githubusercontent.com/33603140/33101331-e9aac40e-cee5-11e7-9339-d62e45e80085.png)

Exact Error: [LookupAnything] Something went wrong looking that up:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pathoschild.Stardew.LookupAnything.DataParser.<GetObjects>d__6.MoveNext() in D:\source\_Stardew\Mods.Pathoschild\LookupAnything\DataParser.cs:line 0
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Pathoschild.Stardew.LookupAnything.GameHelper.<>c.<.cctor>b__30_0() in D:\source\_Stardew\Mods.Pathoschild\LookupAnything\GameHelper.cs:line 28
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Pathoschild.Stardew.LookupAnything.GameHelper.GetFullShipmentAchievementItems() in D:\source\_Stardew\Mods.Pathoschild\LookupAnything\GameHelper.cs:line 69
   at Pathoschild.Stardew.LookupAnything.Framework.Subjects.ItemSubject.<GetData>d__7.MoveNext() in D:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Subjects\ItemSubject.cs:line 255
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Pathoschild.Stardew.LookupAnything.Components.LookupMenu..ctor(ISubject subject, Metadata metadata, IMonitor monitor, IReflectionHelper reflectionHelper, Int32 scroll, Boolean showDebugFields, Action`1 showNewPage) in D:\source\_Stardew\Mods.Pathoschild\LookupAnything\Components\LookupMenu.cs:line 93
   at Pathoschild.Stardew.LookupAnything.LookupAnythingMod.<>c__DisplayClass15_0.<ShowLookupFor>b__0() in D:\source\_Stardew\Mods.Pathoschild\LookupAnything\LookupAnythingMod.cs:line 279
   at Pathoschild.Stardew.Common.CommonHelper.InterceptErrors(IMonitor monitor, String verb, String detailedVerb, Action action, Action`1 onError) in D:\source\_Stardew\Mods.Pathoschild\Common\CommonHelper.cs:line 214
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
[SMAPI] An error occured in the base update loop: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StardewValley.Object.getDescription()
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550

**Comment by Pathoschild** [comment]
@pollywogpixels One of your XNB mods likely replaced `ObjectInformation.xnb` with an older or broken format. This doesn't only affect Lookup Anything, I see the game itself is also throwing errors when reading object data. You can [reset your content files](https://stardewvalleywiki.com/Modding:Player_FAQs#Reset_your_content_files) and remove `XNBLoader\ModContent\ObjectInformation.xnb` to fix it.
