### ISSUE TITLE
[Tractor Mod] error logged when game menu opens with no tractor

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#201]
If you open the game menu on a save with no tractor, you get this error ([log](https://log.smapi.io/afHrzUq3)):

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pathoschild.Stardew.TractorMod.ModEntry.MenuEvents_MenuChanged(Object sender, EventArgsClickableMenuChanged e) in C:\source\_Stardew\Mods.Pathoschild\TractorMod\ModEntry.cs:line 168
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 54
```

**Comment by Pathoschild** [comment]
Fixed in `develop` via #202 for the upcoming Tractor Mod 4.4.1.
