### ISSUE TITLE
[Content Patcher] beta: asset load loop when loading XNB files

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#269]
When loading a local XNB asset, Content Patcher (sometimes?) shows the following error:
```
[16:27:05 WARN SMAPI] Broke loop while loading asset 'Portraits\Maru'.
[16:27:05 TRACE SMAPI] Bypassing mod loaders for this asset. Stack trace:
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at StardewModdingAPI.Framework.SContentManager.LoadImpl[T](String assetName, LanguageCode language) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 428
   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName, LanguageCode language) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 146
   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 111
   at StardewModdingAPI.Framework.ModHelpers.ContentHelper.Load[T](String key, ContentSource source) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\ModHelpers\ContentHelper.cs:line 132
   at StardewModdingAPI.Framework.ContentPack.LoadAsset[T](String key) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\ContentPack.cs:line 67
   at ContentPatcher.Framework.ManagedContentPack.Load[T](String key)
   at ContentPatcher.Framework.Patches.LoadPatch.Load[T](IAssetInfo asset)
   at ContentPatcher.Framework.PatchManager.Load[T](IAssetInfo asset)
   at StardewModdingAPI.Framework.SContentManager.ApplyLoader[T](IAssetInfo info) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 505
   at StardewModdingAPI.Framework.SContentManager.<>c__DisplayClass45_0`1.<LoadImpl>b__0() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 437
   at StardewModdingAPI.Framework.Utilities.ContextHash`1.Track[TResult](T key, Func`1 action) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Utilities\ContextHash.cs:line 53
   at StardewModdingAPI.Framework.SContentManager.LoadImpl[T](String assetName, LanguageCode language) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 433
   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName, LanguageCode language) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 146
   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 111
   at StardewModdingAPI.Framework.ModHelpers.ContentHelper.Load[T](String key, ContentSource source) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\ModHelpers\ContentHelper.cs:line 132
   at StardewModdingAPI.Framework.ContentPack.LoadAsset[T](String key) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\ContentPack.cs:line 67
   at ContentPatcher.Framework.ManagedContentPack.Load[T](String key)
   at ContentPatcher.Framework.Patches.LoadPatch.Load[T](IAssetInfo asset)
   at ContentPatcher.Framework.PatchManager.Load[T](IAssetInfo asset)
   at StardewModdingAPI.Framework.SContentManager.ApplyLoader[T](IAssetInfo info) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 505
   at StardewModdingAPI.Framework.SContentManager.<>c__DisplayClass45_0`1.<LoadImpl>b__0() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 437
   at StardewModdingAPI.Framework.Utilities.ContextHash`1.Track[TResult](T key, Func`1 action) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Utilities\ContextHash.cs:line 53
   at StardewModdingAPI.Framework.SContentManager.LoadImpl[T](String assetName, LanguageCode language) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 433
   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName, LanguageCode language) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 177
   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs:line 111
   at StardewValley.Game1.loadForNewGame(Boolean loadedGame) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 1598
   at StardewValley.SaveGame.<>c.<getLoadEnumerator>b__55_1() in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\SaveGame.cs:line 904
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

See:
* [full log](https://log.smapi.io/gKHQDJgM)
* [sample content pack](https://github.com/Pathoschild/StardewMods/files/2019982/CP.NerdyHotMaru.zip)

[Reported in the forums](https://community.playstarbound.com/threads/content-patcher.141420/page-5#post-3281282).

**Comment by Pathoschild** [comment]
I can no longer reproduce this with the latest version of SMAPI; likely fixed by some of the content fixes in SMAPI.
