### ISSUE TITLE
[Automate] Error Processing Machines

### ISSUE THREAD

**Issue by damonmensch** [Pathoschild/LookupAnything#289]
I loaded my game today and now i'm getting the following error.
`[00:14:19 ERROR Automate] Something went wrong processing machines:
System.InvalidCastException: Can't convert the StardewValley.Locations.Town::garbageChecked field from Netcode.NetArray`2[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Netcode.NetBool, Netcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] to System.Boolean[].
   at StardewModdingAPI.Framework.Reflection.ReflectedField`1.GetValue() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\ReflectedField.cs:line 67
   at Pathoschild.Stardew.Automate.Framework.Machines.Tiles.TrashCanMachine..ctor(Town town, Vector2 tile, Int32 trashCanIndex, IReflectionHelper reflection) in C:\source\_Stardew\Mods.Pathoschild\Automate\Framework\Machines\Tiles\TrashCanMachine.cs:line 36
   at Pathoschild.Stardew.Automate.Framework.MachineFactory.TryGetTileMachine(GameLocation location, Vector2 tile, IReflectionHelper reflection, IMachine& machine, Vector2& size) in C:\source\_Stardew\Mods.Pathoschild\Automate\Framework\MachineFactory.cs:line 300
   at Pathoschild.Stardew.Automate.Framework.MachineFactory.TryGetMachine(GameLocation location, Vector2 tile, IReflectionHelper reflection, IMachine& machine, Vector2& size) in C:\source\_Stardew\Mods.Pathoschild\Automate\Framework\MachineFactory.cs:line 183
   at Pathoschild.Stardew.Automate.Framework.MachineFactory.FloodFillGroup(MachineGroupBuilder group, GameLocation location, Vector2 origin, ISet`1 visited, IReflectionHelper reflection) in C:\source\_Stardew\Mods.Pathoschild\Automate\Framework\MachineFactory.cs:line 103
   at Pathoschild.Stardew.Automate.Framework.MachineFactory.<GetMachineGroups>d__3.MoveNext() in C:\source\_Stardew\Mods.Pathoschild\Automate\Framework\MachineFactory.cs:line 56
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Pathoschild.Stardew.Automate.ModEntry.ReloadMachinesIn(GameLocation location) in C:\source\_Stardew\Mods.Pathoschild\Automate\ModEntry.cs:line 227
   at Pathoschild.Stardew.Automate.ModEntry.GameEvents_UpdateTick(Object sender, EventArgs e) in C:\source\_Stardew\Mods.Pathoschild\Automate\ModEntry.cs:line 170`

That's the full error message in the log and it keeps repeating it every second the game is loaded until it crashed the program.
I am using the following:
Microsoft Windows 10 Pro
Stardew Valley 1.3.20
SMAPI 2.6-beta.16
Automate 1.10-beta.7

I have the full log file attached.
[SMAPI-latest.txt](https://github.com/Pathoschild/StardewMods/files/2117850/SMAPI-latest.txt)

**Comment by Pathoschild** [comment]
Automate broke in today's Stardew Valley 1.3.20 update. I'll be posting an update tomorrow, but there's [an unofficial version](https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-3.142524/page-18#post-3291487) available in the meantime.

**Comment by Pathoschild** [comment]
This was fixed in yesterday's Automate 1.10-beta.8 update.
