### ISSUE TITLE
Something went wrong processing machines

### ISSUE THREAD

**Issue by Skipper97** [Pathoschild/LookupAnything#772]
**SMAPI Log:** https://smapi.io/log/8bf4d78046074eeb8083397fb0b1bed1

Error started to occur after placing Junimo Chest next to a bunch of machines in Farm House Cellar.
Before that I've already had multiple Junimo Chests in other places and never encountered any problems.

```
[Automate] Something went wrong processing machines:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at DaLion.Common.Integrations.Automate.ExtendedAutomateAPI.GetClosestContainerTo(Object machine, GameLocation location) in C:\dev\sdv-mods\ImmersiveValley\Common\Integrations\Automate\ExtendedAutomateAPI.cs:line 95
   at DaLion.Stardew.Professions.Framework.Patches.Integrations.Automate.GenericObjectMachinePatches.ApplyArtisanPerks(Object machine, GameLocation location, Item sample) in C:\dev\sdv-mods\ImmersiveValley\ImmersiveProfessions\Framework\Patches\Integrations\Automate\GenericObjectMachinePatches.cs:line 110
   at Pathoschild.Stardew.Automate.Framework.GenericObjectMachine`1[[StardewValley.Object, Stardew Valley, Version=1.5.6.22018, Culture=neutral, PublicKeyToken=null]].GenericPullRecipe_PatchedBy<DaLion.ImmersiveProfessions__DaLion.ImmersiveTweaks>(GenericObjectMachine`1 this, IStorage storage, IRecipe[] recipes, Item& input)
   at Pathoschild.Stardew.Automate.Framework.Machines.Objects.KegMachine.SetInput(IStorage input)
   at Pathoschild.Stardew.Automate.Framework.MachineGroup.Automate()
   at Pathoschild.Stardew.Automate.ModEntry.OnUpdateTicked(Object sender, UpdateTickedEventArgs e)


```

**Comment by Pathoschild** [comment]
Hi! That's an error in the Immersive Tweaks or Immersive Professions code; I suggest reporting it to those mods' author so they can look into it.
