### ISSUE TITLE
Cannot lookup "Preserves Jar" item after 1.41.6 update.

### ISSUE THREAD

**Issue by febzen** [Pathoschild/LookupAnything#913]
Cannot lookup "Preserves Jar" item after 1.41.6 update.

**Log file**
https://smapi.io/log/e06118f55c2d416ba4e3202cf955788e

**Screenshots**
![20240419185414_1](https://github.com/Pathoschild/StardewMods/assets/88053316/e652c9dc-7911-420b-a907-b6c53c73ac88)

**Comment by MrTeal** [comment]
Same for me. Here is the message from the console:

`[Lookup Anything] Something went wrong looking that up:
System.NullReferenceException: Object reference not set to an instance of an object.
   at StardewValley.Object.loadDisplayName() in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 753
   at StardewValley.Object.get_DisplayName() in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 380
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.TryCreateItemEntry(String id, RecipeIngredientModel ingredient) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 351
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.<>c__DisplayClass8_1.<BuildRecipeGroups>b__8(String[] inputIds) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 199
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.BuildRecipeGroups(Item ingredient, RecipeModel[] rawRecipes)+MoveNext() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 178
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField..ctor(GameHelper gameHelper, String label, Item ingredient, RecipeModel[] recipes) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 27
   at Pathoschild.Stardew.LookupAnything.Framework.Lookups.Items.ItemSubject.GetData()+MoveNext() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Lookups\Items\ItemSubject.cs:line 286
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Pathoschild.Stardew.LookupAnything.Components.LookupMenu..ctor(ISubject subject, IMonitor monitor, IReflectionHelper reflectionHelper, Int32 scroll, Boolean showDebugFields, Boolean forceFullScreen, Action`1 showNewPage) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Components\LookupMenu.cs:line 37
   at Pathoschild.Stardew.LookupAnything.ModEntry.<>c__DisplayClass21_0.<ShowLookupFor>b__0() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\ModEntry.cs:line 262
   at Pathoschild.Stardew.Common.CommonHelper.InterceptErrors(IMonitor monitor, String verb, String detailedVerb, Action action, Action`1 onError) in E:\source\_Stardew\Mods.Pathoschild\Common\CommonHelper.cs:line 442
`

**Comment by Yusuf-shaik** [comment]
same here. My logs after trying it twice:

[Lookup Anything] Something went wrong looking that up:
System.NullReferenceException: Object reference not set to an instance of an object.
   at StardewValley.Object.loadDisplayName() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 753
   at StardewValley.Object.get_DisplayName() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 380
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.TryCreateItemEntry(String id, RecipeIngredientModel ingredient) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 351
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.<>c__DisplayClass8_1.<BuildRecipeGroups>b__8(String[] inputIds) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 199
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.BuildRecipeGroups(Item ingredient, RecipeModel[] rawRecipes)+MoveNext() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 178
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField..ctor(GameHelper gameHelper, String label, Item ingredient, RecipeModel[] recipes) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 27
   at Pathoschild.Stardew.LookupAnything.Framework.Lookups.Items.ItemSubject.GetData()+MoveNext() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Lookups\Items\ItemSubject.cs:line 286
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Pathoschild.Stardew.LookupAnything.Components.LookupMenu..ctor(ISubject subject, IMonitor monitor, IReflectionHelper reflectionHelper, Int32 scroll, Boolean showDebugFields, Boolean forceFullScreen, Action`1 showNewPage) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Components\LookupMenu.cs:line 37
   at Pathoschild.Stardew.LookupAnything.ModEntry.<>c__DisplayClass21_0.<ShowLookupFor>b__0() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\ModEntry.cs:line 262
   at Pathoschild.Stardew.Common.CommonHelper.InterceptErrors(IMonitor monitor, String verb, String detailedVerb, Action action, Action`1 onError) in E:\source\_Stardew\Mods.Pathoschild\Common\CommonHelper.cs:line 442
[Lookup Anything] Something went wrong looking that up:
System.NullReferenceException: Object reference not set to an instance of an object.
   at StardewValley.Object.loadDisplayName() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 753
   at StardewValley.Object.get_DisplayName() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 380
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.TryCreateItemEntry(String id, RecipeIngredientModel ingredient) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 351
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.<>c__DisplayClass8_1.<BuildRecipeGroups>b__8(String[] inputIds) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 199
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField.BuildRecipeGroups(Item ingredient, RecipeModel[] rawRecipes)+MoveNext() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 178
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Pathoschild.Stardew.LookupAnything.Framework.Fields.ItemRecipesField..ctor(GameHelper gameHelper, String label, Item ingredient, RecipeModel[] recipes) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Fields\ItemRecipesField.cs:line 27
   at Pathoschild.Stardew.LookupAnything.Framework.Lookups.Items.ItemSubject.GetData()+MoveNext() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Framework\Lookups\Items\ItemSubject.cs:line 286
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Pathoschild.Stardew.LookupAnything.Components.LookupMenu..ctor(ISubject subject, IMonitor monitor, IReflectionHelper reflectionHelper, Int32 scroll, Boolean showDebugFields, Boolean forceFullScreen, Action`1 showNewPage) in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\Components\LookupMenu.cs:line 37
   at Pathoschild.Stardew.LookupAnything.ModEntry.<>c__DisplayClass21_0.<ShowLookupFor>b__0() in E:\source\_Stardew\Mods.Pathoschild\LookupAnything\ModEntry.cs:line 262
   at Pathoschild.Stardew.Common.CommonHelper.InterceptErrors(IMonitor monitor, String verb, String detailedVerb, Action action, Action`1 onError) in E:\source\_Stardew\Mods.Pathoschild\Common\CommonHelper.cs:line 442

**Comment by cartycrabber** [comment]
I have the same issue with the exact same error log when looking up any kind of Roe.

**Comment by Pathoschild** [comment]
That was a game bug fixed in Stardew Valley 1.6.6. Thanks for reporting it!
